export const AuthConst = {

    SIGNUP_REQUEST: 'SIGNUP_REQUEST',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',

    GENDER_REQUEST: 'GENDER_REQUEST',
    GENDER_SUCCESS: 'GENDER_SUCCESS',
    GENDER_FAILURE: 'GENDER_FAILURE',

    VERIFY_REQUEST: 'VERIFY_REQUEST',
    VERIFY_SUCCESS: 'VERIFY_SUCCESS',
    VERIFY_FAILURE: 'VERIFY_FAILURE',

    VERIFY_AUTH_REQUEST: 'VERIFY_AUTH_REQUEST',
    VERIFY_AUTH_SUCCESS: 'VERIFY_AUTH_SUCCESS',
    VERIFY_AUTH_FAILURE: 'VERIFY_AUTH_FAILURE',

    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
    FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
    FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE',

    RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

    LOGOUT: 'USER_LOGOUT'
};