export const BankConst = {

    CREDIT_BANK_REQUEST: 'CREDIT_BANK_REQUEST',
    CREDIT_BANK_SUCCESS: 'CREDIT_BANK_SUCCESS',
    CREDIT_BANK_FAILURE: 'CREDIT_BANK_FAILURE',

    VERIFY_BANK_REQUEST: 'VERIFY_BANK_REQUEST',
    VERIFY_BANK_SUCCESS: 'VERIFY_BANK_SUCCESS',
    VERIFY_BANK_FAILURE: 'VERIFY_BANK_FAILURE',

    REMOVE_BANK_REQUEST: 'REMOVE_BANK_REQUEST',
    REMOVE_BANK_SUCCESS: 'REMOVE_BANK_SUCCESS',
    REMOVE_BANK_FAILURE: 'REMOVE_BANK_FAILURE',

    FETCH_BANKS_REQUEST: 'FETCH_BANKS_REQUEST',
    FETCH_BANKS_SUCCESS: 'FETCH_BANKS_SUCCESS',
    FETCH_BANKS_FAILURE: 'FETCH_BANKS_FAILURE',
};