export const CardConst = {

    CHARGE_CARD_REQUEST: 'CHARGE_CARD_REQUEST',
    CHARGE_CARD_SUCCESS: 'CHARGE_CARD_SUCCESS',
    CHARGE_CARD_FAILURE: 'CHARGE_CARD_FAILURE',

    VERIFY_CARD_REQUEST: 'VERIFY_CARD_REQUEST',
    VERIFY_CARD_SUCCESS: 'VERIFY_CARD_SUCCESS',
    VERIFY_CARD_FAILURE: 'VERIFY_CARD_FAILURE',

    REMOVE_CARD_REQUEST: 'REMOVE_CARD_REQUEST',
    REMOVE_CARD_SUCCESS: 'REMOVE_CARD_SUCCESS',
    REMOVE_CARD_FAILURE: 'REMOVE_CARD_FAILURE',

    LOG_TRX_REQUEST: 'LOG_TRX_REQUEST',
    LOG_TRX_SUCCESS: 'LOG_TRX_SUCCESS',
    LOG_TRX_FAILURE: 'LOG_TRX_FAILURE',

    FETCH_CARDS_REQUEST: 'FETCH_CARDS_REQUEST',
    FETCH_CARDS_SUCCESS: 'FETCH_CARDS_SUCCESS',
    FETCH_CARDS_FAILURE: 'FETCH_CARDS_FAILURE',
};