export const ImportConst = {

    IMPORT_COUNTRIES_REQUEST: 'IMPORT_COUNTRIES_REQUEST',
    IMPORT_COUNTRIES_SUCCESS: 'IMPORT_COUNTRIES_SUCCESS',
    IMPORT_COUNTRIES_FAILURE: 'IMPORT_COUNTRIES_FAILURE',

    IMPORT_STATES_REQUEST: 'IMPORT_STATES_REQUEST',
    IMPORT_STATES_SUCCESS: 'IMPORT_STATES_SUCCESS',
    IMPORT_STATES_FAILURE: 'IMPORT_STATES_FAILURE',
};