export const LoanConst = {

    LOAN_OFFERS_REQUEST: 'LOAN_OFFERS_REQUEST',
    LOAN_OFFERS_SUCCESS: 'LOAN_OFFERS_SUCCESS',
    LOAN_OFFERS_FAILURE: 'LOAN_OFFERS_FAILURE',

    LOAN_REQUESTS_REQUEST: 'LOAN_REQUESTS_REQUEST',
    LOAN_REQUESTS_SUCCESS: 'LOAN_REQUESTS_SUCCESS',
    LOAN_REQUESTS_FAILURE: 'LOAN_REQUESTS_FAILURE',
};