export const LoanConst = {

    LOAN_OFFERS_REQUEST: 'LOAN_OFFERS_REQUEST',
    LOAN_OFFERS_SUCCESS: 'LOAN_OFFERS_SUCCESS',
    LOAN_OFFERS_FAILURE: 'LOAN_OFFERS_FAILURE',

    LOAN_REQUESTS_REQUEST: 'LOAN_REQUESTS_REQUEST',
    LOAN_REQUESTS_SUCCESS: 'LOAN_REQUESTS_SUCCESS',
    LOAN_REQUESTS_FAILURE: 'LOAN_REQUESTS_FAILURE',

    LOAN_CONST_REQUEST: 'LOAN_CONST_REQUEST',
    LOAN_CONST_SUCCESS: 'LOAN_CONST_SUCCESS',
    LOAN_CONST_FAILURE: 'LOAN_CONST_FAILURE',

    LOAN_OFFER_REQUEST: 'LOAN_OFFER_REQUEST',
    LOAN_OFFER_SUCCESS: 'LOAN_OFFER_SUCCESS',
    LOAN_OFFER_FAILURE: 'LOAN_OFFER_FAILURE',

    LOAN_REQUEST_REQUEST: 'LOAN_REQUEST_REQUEST',
    LOAN_REQUEST_SUCCESS: 'LOAN_REQUEST_SUCCESS',
    LOAN_REQUEST_FAILURE: 'LOAN_REQUEST_FAILURE',

    LOAN_APPLY_REQUEST: 'LOAN_APPLY_REQUEST',
    LOAN_APPLY_SUCCESS: 'LOAN_APPLY_SUCCESS',
    LOAN_APPLY_FAILURE: 'LOAN_APPLY_FAILURE',

    LOAN_APPLICATIONS_REQUEST: 'LOAN_APPLICATIONS_REQUEST',
    LOAN_APPLICATIONS_SUCCESS: 'LOAN_APPLICATIONS_SUCCESS',
    LOAN_APPLICATIONS_FAILURE: 'LOAN_APPLICATIONS_FAILURE',

    LOAN_APPLICATION_GRANT_REQUEST: 'LOAN_APPLICATION_GRANT_REQUEST',
    LOAN_APPLICATION_GRANT_SUCCESS: 'LOAN_APPLICATION_GRANT_SUCCESS',
    LOAN_APPLICATION_GRANT_FAILURE: 'LOAN_APPLICATION_GRANT_FAILURE',

    LOAN_APPLICATION_CANCEL_REQUEST: 'LOAN_APPLICATION_CANCEL_REQUEST',
    LOAN_APPLICATION_CANCEL_SUCCESS: 'LOAN_APPLICATION_CANCEL_SUCCESS',
    LOAN_APPLICATION_CANCEL_FAILURE: 'LOAN_APPLICATION_CANCEL_FAILURE',

    LOAN_REPAYMENT_REQUEST: 'LOAN_REPAYMENT_REQUEST',
    LOAN_REPAYMENT_SUCCESS: 'LOAN_REPAYMENT_SUCCESS',
    LOAN_REPAYMENT_FAILURE: 'LOAN_REPAYMENT_FAILURE',

    LOAN_REPAYMENT_HISTORY_REQUEST: 'LOAN_REPAYMENT_HISTORY_REQUEST',
    LOAN_REPAYMENT_HISTORY_SUCCESS: 'LOAN_REPAYMENT_HISTORY_SUCCESS',
    LOAN_REPAYMENT_HISTORY_FAILURE: 'LOAN_REPAYMENT_HISTORY_FAILURE',
};