export const LoanConst = {

    LOAN_OFFERS_REQUEST: 'LOAN_OFFERS_REQUEST',
    LOAN_OFFERS_SUCCESS: 'LOAN_OFFERS_SUCCESS',
    LOAN_OFFERS_FAILURE: 'LOAN_OFFERS_FAILURE',

    LOAN_REQUESTS_REQUEST: 'LOAN_REQUESTS_REQUEST',
    LOAN_REQUESTS_SUCCESS: 'LOAN_REQUESTS_SUCCESS',
    LOAN_REQUESTS_FAILURE: 'LOAN_REQUESTS_FAILURE',

    LOAN_CONST_REQUEST: 'LOAN_CONST_REQUEST',
    LOAN_CONST_SUCCESS: 'LOAN_CONST_SUCCESS',
    LOAN_CONST_FAILURE: 'LOAN_CONST_FAILURE',

    LOAN_OFFER_REQUEST: 'LOAN_OFFER_REQUEST',
    LOAN_OFFER_SUCCESS: 'LOAN_OFFER_SUCCESS',
    LOAN_OFFER_FAILURE: 'LOAN_OFFER_FAILURE',

    LOAN_REQUEST_REQUEST: 'LOAN_REQUEST_REQUEST',
    LOAN_REQUEST_SUCCESS: 'LOAN_REQUEST_SUCCESS',
    LOAN_REQUEST_FAILURE: 'LOAN_REQUEST_FAILURE',
};