export const ProfileConst = {

    PROFILE_RATING_REQUEST: 'PROFILE_RATING_REQUEST',
    PROFILE_RATING_SUCCESS: 'PROFILE_RATING_SUCCESS',
    PROFILE_RATING_FAILURE: 'PROFILE_RATING_FAILURE',

    PROFILE_INFO_UPDATE_REQUEST: 'PROFILE_INFO_UPDATE_REQUEST',
    PROFILE_INFO_UPDATE_SUCCESS: 'PROFILE_INFO_UPDATE_SUCCESS',
    PROFILE_INFO_UPDATE_FAILURE: 'PROFILE_INFO_UPDATE_FAILURE',

    PROFILE_PICTURE_UPDATE_REQUEST: 'PROFILE_PICTURE_UPDATE_REQUEST',
    PROFILE_PICTURE_UPDATE_SUCCESS: 'PROFILE_PICTURE_UPDATE_SUCCESS',
    PROFILE_PICTURE_UPDATE_FAILURE: 'PROFILE_PICTURE_UPDATE_FAILURE',

    PROFILE_PICTURE_REMOVE_REQUEST: 'PROFILE_PICTURE_REMOVE_REQUEST',
    PROFILE_PICTURE_REMOVE_SUCCESS: 'PROFILE_PICTURE_REMOVE_SUCCESS',
    PROFILE_PICTURE_REMOVE_FAILURE: 'PROFILE_PICTURE_REMOVE_FAILURE',
};