export const ReviewConst = {

    REVIEW_USER_REQUEST: 'REVIEW_USER_REQUEST',
    REVIEW_USER_SUCCESS: 'REVIEW_USER_SUCCESS',
    REVIEW_USER_FAILURE: 'REVIEW_USER_FAILURE',

    EDIT_REVIEW_REQUEST: 'EDIT_REVIEW_REQUEST',
    EDIT_REVIEW_SUCCESS: 'EDIT_REVIEW_SUCCESS',
    EDIT_REVIEW_FAILURE: 'EDIT_REVIEW_FAILURE',

    DELETE_REVIEW_REQUEST: 'DELETE_REVIEW_REQUEST',
    DELETE_REVIEW_SUCCESS: 'DELETE_REVIEW_SUCCESS',
    DELETE_REVIEW_FAILURE: 'DELETE_REVIEW_FAILURE',

    FETCH_REVIEWS_REQUEST: 'FETCH_REVIEWS_REQUEST',
    FETCH_REVIEWS_SUCCESS: 'FETCH_REVIEWS_SUCCESS',
    FETCH_REVIEWS_FAILURE: 'FETCH_REVIEWS_FAILURE',
};